- hosts: all
  tasks:
   - name: stop container
     shell: docker container stop dockerandansible
   - name: remove container
     shell: docker container rm dockerandansible
   - name: remove docker image
     shell: docker image rm -f sabaridelfi/dockerandwebapp3
   - name: create new container
     shell: docker run -itd --name dockerandansible -p 9000:80 sabaridelfi/dockerandwebapp3
